language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t npulimood/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true npulimood/docker-react npm run test